### ISSUE TITLE
Dose not work on MCserver 1.10.2 

### ISSUE THREAD

**Issue by Tollainmear** [VcSaJen/YourCustomPaintings#1]
Test with 
```
 [Server thread/INFO]: SpongeForge
    Minecraft: 1.10.2
    SpongeAPI: 5.2.0-SNAPSHOT-c675e80
    SpongeForge: 1.10.2-2281-5.2.0-BETA-2575
    Minecraft Forge: 12.18.3.2422
```

Error Report：

While initialize：

```
  [Sponge]: Could not pass FMLInitializationEvent to Plugin{id=yourcustompaintings, name=YourCustomPaintings, version=1.0.0.10, description=Upload your own custom paintings to minecraft server!, source=D:\minecraft\Sponge-1.10.2\mods\yourcustompaintings-1.0.0.10.jar}
java.lang.NoSuchMethodError: org.spongepowered.api.service.permission.PermissionService.newDescriptionBuilder(Ljava/lang/Object;)Lorg/spongepowered/api/service/permission/PermissionDescription$Builder;
        at com.vcsajen.yourcustompaintings.YourCustomPaintings.lambda$onGameInitialization$6(YourCustomPaintings.java:1272) ~[YourCustomPaintings.class:?]
        at java.util.Optional.map(Unknown Source) ~[?:1.8.0_144]
        at com.vcsajen.yourcustompaintings.YourCustomPaintings.onGameInitialization(YourCustomPaintings.java:1271) ~[YourCustomPaintings.class:?]
        at org.spongepowered.common.event.listener.GameInitializationEventListener_YourCustomPaintings_onGameInitialization26.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2281-5.2.0-BETA-2575]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:313) [SpongeModEventManager.class:1.10.2-2281-5.2.0-BETA-2575]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:342) [SpongeModEventManager.class:1.10.2-2281-5.2.0-BETA-2575]
        at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:234) [SpongeMod.class:1.10.2-2281-5.2.0-BETA-2575]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_144]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.10.2.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.10.2.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.10.2.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.10.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.10.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243) [LoadController.class:?]
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221) [LoadController.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_144]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.10.2.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.10.2.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.10.2.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.10.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.10.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.redirect$onPost$zzb000(LoadController.java:561) [LoadController.class:?]
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145) [LoadController.class:?]
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:805) [Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108) [FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:333) [FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:214) [ld.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]

```
While right click "Painting  Placer":

```
  [Sponge]: Could not pass InteractBlockEvent$Secondary$MainHand$Impl to Plugin{id=yourcustompaintings, name=YourCustomPaintings, version=1.0.0.10, description=Upload your own custom paintings to minecraft server!, source=D:\minecraft\Sponge-1.10.2\mods\yourcustompaintings-1.0.0.10.jar}
java.lang.IllegalArgumentException: Failed offer transaction!
        at org.spongepowered.api.data.value.mutable.CompositeValueStore.tryOffer(CompositeValueStore.java:440) ~[CompositeValueStore.class:1.10.2-2281-5.2.0-BETA-2575]
        at com.vcsajen.yourcustompaintings.PaintingPlacer.placePaintingIfPossible(PaintingPlacer.java:176) ~[PaintingPlacer.class:?]
        at com.vcsajen.yourcustompaintings.PaintingPlacer.onInteractBlockEvent(PaintingPlacer.java:221) ~[PaintingPlacer.class:?]
        at org.spongepowered.common.event.listener.MainHandListener_PaintingPlacer_onInteractBlockEvent36.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2281-5.2.0-BETA-2575]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:313) ~[SpongeModEventManager.class:1.10.2-2281-5.2.0-BETA-2575]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:297) ~[SpongeModEventManager.class:1.10.2-2281-5.2.0-BETA-2575]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:338) ~[SpongeModEventManager.class:1.10.2-2281-5.2.0-BETA-2575]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:326) ~[SpongeModEventManager.class:1.10.2-2281-5.2.0-BETA-2575]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:143) ~[SpongeImpl.class:1.10.2-2281-5.2.0-BETA-2575]
        at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractBlockEventSecondary(SpongeCommonEventFactory.java:541) ~[SpongeCommonEventFactory.class:1.10.2-2281-5.2.0-BETA-2575]
        at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractBlockEventSecondary(SpongeCommonEventFactory.java:531) ~[SpongeCommonEventFactory.class:1.10.2-2281-5.2.0-BETA-2575]
        at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:1186) ~[lv.class:?]
        at net.minecraft.network.NetHandlerPlayServer.redirect$onProcessRightClickBlock$zhf000(NetHandlerPlayServer.java:2292) ~[me.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:679) ~[me.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[jj.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[jj.class:?]
        at org.spongepowered.common.network.PacketUtil.lambda$onProcessPacket$0(PacketUtil.java:157) ~[PacketUtil.class:1.10.2-2281-5.2.0-BETA-2575]
        at org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseTracker.java:163) [CauseTracker.class:1.10.2-2281-5.2.0-BETA-2575]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:156) [PacketUtil.class:1.10.2-2281-5.2.0-BETA-2575]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjj000(SourceFile:539) [fl$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:238) [SpongeImplHooks.class:1.10.2-2281-5.2.0-BETA-2575]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zhp000(MinecraftServer.java:3951) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
```

**Comment by SjsolisZXA** [comment]
Same issue here and I'd also like to motion for a 1.10.2 version of this amazing and vital plugin.
